project:
  type: website

website:
  title: "nsaadig16"
  navbar:
    left:
      - href: index.qmd
        text: About me

format:
  html:
    theme:
      - slates
    fontsize: large
    css: styles.css
    toc: true



