project:
  type: website

website:
  site-url: https://nsaadig16.github.io
  repo-url: nsaadig16/nsaadig16.github.io
  repo-branch: gh-pages
  favicon: /imgs/favicon.ico
  search: false
  title: "nsaadig16"
  navbar:
    logo: imgs/favicon.ico
    collapse: true
    left:
      - href: index.qmd
        text: About me
      - href: projects.qmd
        text: Projects
    right:
      - icon: bi bi-file-earmark-pdf-fill
        text: Get my CV
        menu:
          - text: English
            href: /cvs/CV_en.pdf
          - text: Castellano
            href: /cvs/CV_es.pdf
          - text: Catal√†
            href: /cvs/CV_ca.pdf


format:
  html:
    fontsize: large
    css: styles.css
    toc: false
    theme:
      light: flatly
      dark: darkly
    toggle: true
    respect-user-color-scheme: true




