project:
  type: website

website:
  favicon: /imgs/favicon.ico
  search: false
  title: "nsaadig16"
  navbar:
    left:
      - href: index.qmd
        text: About me
      - href: projects.qmd
        text: Projects
    right:
      - icon: bi bi-file-earmark-pdf-fill
        text: Get my CV
        menu:
          - text: English

            href: /cvs/CV_en.pdf
          - text: Castellano
            href: /cvs/CV_es.pdf
          - text: Catal√†
            href: /cvs/CV_ca.pdf


format:
  html:
    fontsize: large
    css: styles.css
    toc: false




